// Code generated by scripts/generate-permissions.sh from the GitHub REST API
// app-permissions schema; DO NOT EDIT.

package input

// Permissions holds the GitHub App permission_<resource> action inputs, one
// field per resource. envconfig binds each field directly from its own
// INPUT_PERMISSION_<RESOURCE> variable; the perm tag carries the resource's
// exact API key for Permissions.toMap().
type Permissions struct {
	Actions                                    string `envconfig:"ACTIONS" perm:"actions"`
	Administration                             string `envconfig:"ADMINISTRATION" perm:"administration"`
	ArtifactMetadata                           string `envconfig:"ARTIFACT_METADATA" perm:"artifact_metadata"`
	Attestations                               string `envconfig:"ATTESTATIONS" perm:"attestations"`
	Checks                                     string `envconfig:"CHECKS" perm:"checks"`
	CodeQuality                                string `envconfig:"CODE_QUALITY" perm:"code_quality"`
	Codespaces                                 string `envconfig:"CODESPACES" perm:"codespaces"`
	Contents                                   string `envconfig:"CONTENTS" perm:"contents"`
	DependabotSecrets                          string `envconfig:"DEPENDABOT_SECRETS" perm:"dependabot_secrets"`
	Deployments                                string `envconfig:"DEPLOYMENTS" perm:"deployments"`
	Discussions                                string `envconfig:"DISCUSSIONS" perm:"discussions"`
	Environments                               string `envconfig:"ENVIRONMENTS" perm:"environments"`
	Issues                                     string `envconfig:"ISSUES" perm:"issues"`
	MergeQueues                                string `envconfig:"MERGE_QUEUES" perm:"merge_queues"`
	Metadata                                   string `envconfig:"METADATA" perm:"metadata"`
	Packages                                   string `envconfig:"PACKAGES" perm:"packages"`
	Pages                                      string `envconfig:"PAGES" perm:"pages"`
	PullRequests                               string `envconfig:"PULL_REQUESTS" perm:"pull_requests"`
	RepositoryCustomProperties                 string `envconfig:"REPOSITORY_CUSTOM_PROPERTIES" perm:"repository_custom_properties"`
	RepositoryHooks                            string `envconfig:"REPOSITORY_HOOKS" perm:"repository_hooks"`
	RepositoryProjects                         string `envconfig:"REPOSITORY_PROJECTS" perm:"repository_projects"`
	SecretScanningAlerts                       string `envconfig:"SECRET_SCANNING_ALERTS" perm:"secret_scanning_alerts"`
	Secrets                                    string `envconfig:"SECRETS" perm:"secrets"`
	SecurityEvents                             string `envconfig:"SECURITY_EVENTS" perm:"security_events"`
	SingleFile                                 string `envconfig:"SINGLE_FILE" perm:"single_file"`
	Statuses                                   string `envconfig:"STATUSES" perm:"statuses"`
	VulnerabilityAlerts                        string `envconfig:"VULNERABILITY_ALERTS" perm:"vulnerability_alerts"`
	Workflows                                  string `envconfig:"WORKFLOWS" perm:"workflows"`
	CustomPropertiesForOrganizations           string `envconfig:"CUSTOM_PROPERTIES_FOR_ORGANIZATIONS" perm:"custom_properties_for_organizations"`
	Members                                    string `envconfig:"MEMBERS" perm:"members"`
	OrganizationAdministration                 string `envconfig:"ORGANIZATION_ADMINISTRATION" perm:"organization_administration"`
	OrganizationCustomRoles                    string `envconfig:"ORGANIZATION_CUSTOM_ROLES" perm:"organization_custom_roles"`
	OrganizationCustomOrgRoles                 string `envconfig:"ORGANIZATION_CUSTOM_ORG_ROLES" perm:"organization_custom_org_roles"`
	OrganizationCustomProperties               string `envconfig:"ORGANIZATION_CUSTOM_PROPERTIES" perm:"organization_custom_properties"`
	OrganizationCopilotSeatManagement          string `envconfig:"ORGANIZATION_COPILOT_SEAT_MANAGEMENT" perm:"organization_copilot_seat_management"`
	OrganizationCopilotAgentSettings           string `envconfig:"ORGANIZATION_COPILOT_AGENT_SETTINGS" perm:"organization_copilot_agent_settings"`
	OrganizationAnnouncementBanners            string `envconfig:"ORGANIZATION_ANNOUNCEMENT_BANNERS" perm:"organization_announcement_banners"`
	OrganizationEvents                         string `envconfig:"ORGANIZATION_EVENTS" perm:"organization_events"`
	OrganizationHooks                          string `envconfig:"ORGANIZATION_HOOKS" perm:"organization_hooks"`
	OrganizationPersonalAccessTokens           string `envconfig:"ORGANIZATION_PERSONAL_ACCESS_TOKENS" perm:"organization_personal_access_tokens"`
	OrganizationPersonalAccessTokenRequests    string `envconfig:"ORGANIZATION_PERSONAL_ACCESS_TOKEN_REQUESTS" perm:"organization_personal_access_token_requests"`
	OrganizationPlan                           string `envconfig:"ORGANIZATION_PLAN" perm:"organization_plan"`
	OrganizationProjects                       string `envconfig:"ORGANIZATION_PROJECTS" perm:"organization_projects"`
	OrganizationPackages                       string `envconfig:"ORGANIZATION_PACKAGES" perm:"organization_packages"`
	OrganizationSecrets                        string `envconfig:"ORGANIZATION_SECRETS" perm:"organization_secrets"`
	OrganizationSelfHostedRunners              string `envconfig:"ORGANIZATION_SELF_HOSTED_RUNNERS" perm:"organization_self_hosted_runners"`
	OrganizationUserBlocking                   string `envconfig:"ORGANIZATION_USER_BLOCKING" perm:"organization_user_blocking"`
	EmailAddresses                             string `envconfig:"EMAIL_ADDRESSES" perm:"email_addresses"`
	Followers                                  string `envconfig:"FOLLOWERS" perm:"followers"`
	GitSshKeys                                 string `envconfig:"GIT_SSH_KEYS" perm:"git_ssh_keys"`
	GpgKeys                                    string `envconfig:"GPG_KEYS" perm:"gpg_keys"`
	InteractionLimits                          string `envconfig:"INTERACTION_LIMITS" perm:"interaction_limits"`
	Profile                                    string `envconfig:"PROFILE" perm:"profile"`
	Starring                                   string `envconfig:"STARRING" perm:"starring"`
	EnterpriseCustomPropertiesForOrganizations string `envconfig:"ENTERPRISE_CUSTOM_PROPERTIES_FOR_ORGANIZATIONS" perm:"enterprise_custom_properties_for_organizations"`
}
