#!/bin/bash
set -euo pipefail

INPUT_JSON="$1"
OUT_GO="internal/input/permissions_gen.go"

# The schema is third-party content (github/rest-api-description): keys must stay in a
# safe charset so they can't break out of the generated Go source.
FIELDS=$(jq -r '
  .components.schemas["app-permissions"].properties | to_entries | .[] |
  .key as $key |
  ($key | if test("^[a-zA-Z0-9_-]+$") then . else error("unexpected permission key: " + .) end) as $safe |
  ($safe | split("_") | map((.[0:1] | ascii_upcase) + .[1:]) | join("")) as $field |
  ($safe | ascii_upcase) as $env |
  "\t" + $field + " string `envconfig:\"" + $env + "\" perm:\"" + $safe + "\"`"
' "$INPUT_JSON")

{
  echo "// Code generated by scripts/generate-permissions.sh from the GitHub REST API"
  echo "// app-permissions schema; DO NOT EDIT."
  echo ""
  echo "package input"
  echo ""
  echo "// Permissions holds the GitHub App permission_<resource> action inputs, one"
  echo "// field per resource. envconfig binds each field directly from its own"
  echo "// INPUT_PERMISSION_<RESOURCE> variable; the perm tag carries the resource's"
  echo "// exact API key for Permissions.toMap()."
  echo "type Permissions struct {"
  echo "$FIELDS"
  echo "}"
} > "$OUT_GO"

gofmt -w "$OUT_GO"
