name: tagpr

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  tagpr:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Create GitHub App Token
        id: token
        uses: yagihash/sts-action@0243739fb1c37f6f31ba9936af010a807a9dd644 # v0.0.1
        with:
          scope: ${{ github.repository }}
          policy: writer

      - uses: Songmu/tagpr@9bbb945b2fb025126186661e27d55485e3fc6df6 # v1.18.3
        env:
          GITHUB_TOKEN: ${{ steps.token.outputs.token }}
