name: tagpr

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  tagpr:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: cicd-sensor/cicd-sensor-action@6511eb44c91d71b2b93d71193b1bf2cb18352f66 # v0.0.38
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
        with:
          persist-credentials: false

      - name: Create GitHub App Token
        id: token
        uses: yagihash/ghmint-action@be57533eef7f69550d06f0c93eede5589158281a # v1.0.0
        with:
          scope: ${{ github.repository }}
          policy: writer

      - uses: Songmu/tagpr@242e22916eb775d6e359959fe3ba5c497de4a01a # v1.20.2
        env:
          GITHUB_TOKEN: ${{ steps.token.outputs.token }}
